    ServerEvents.recipes(event=>{
        //鱼片相关
        event.remove({type:"farmersdelight:cutting",output:"farmersdelight:cod_slice"})
        event.remove({type:"farmersdelight:cutting",output:"farmersdelight:salmon_slice"})
        event.remove({type:"farmersdelight:cutting",output:"crabbersdelight:pufferfish_slice"})
        event.remove({type:"farmersdelight:cutting",output:"crabbersdelight:tropical_fish_slice"})
        event.remove({type:"farmersdelight:cutting",output:"alexsdelight:raw_catfish_slice"})
        event.remove({type:"farmersdelight:cutting",output:"oceansdelight:fugu_slice"})
        event.remove({output:'oceansdelight:fugu_roll'})
        event.recipes.farmersdelight.cutting("cod","#forge:tools/knives",Item.of("farmersdelight:cod_slice",3))
        event.recipes.farmersdelight.cutting("salmon","#forge:tools/knives",Item.of("farmersdelight:salmon_slice",3))
        event.recipes.farmersdelight.cutting("pufferfish","#forge:tools/knives",Item.of("crabbersdelight:pufferfish_slice",3))
        event.recipes.farmersdelight.cutting("tropical_fish","#forge:tools/knives",Item.of("crabbersdelight:tropical_fish_slice",3))
        event.recipes.farmersdelight.cutting("alexsmobs:raw_catfish","#forge:tools/knives",Item.of("alexsdelight:raw_catfish_slice",3))
        //寿司相关
        event.shapeless('oceansdelight:fugu_roll',['crabbersdelight:pufferfish_slice','crabbersdelight:pufferfish_slice','farmersdelight:cooked_rice'])
        //炖汤相关
        const BOW = 'botania:water_bowl'
        event.remove({id:"create:empty_botania_water_bowl_of_minecraft_water"})
        event.recipes.create.filling('botania:water_bowl',['bowl',Fluid.of('water',250)])
        event.recipes.create.emptying([Fluid.of('water',250),"bowl"],'botania:water_bowl')
        //大骨汤
        event.remove({output:'farmersdelight:bone_broth'})
        event.recipes.farmersdelight.cooking(['bone',['#forge:mushrooms','bone']],'farmersdelight:bone_broth',1.0,10*20,BOW)
        event.recipes.create.mixing('farmersdelight:bone_broth',['minecraft:bone',['#forge:mushrooms','bone'],Fluid.of('minecraft:water',250),'bowl']).heated()
        //牛肉炖
        event.remove({output:"farmersdelight:beef_stew"})
        event.recipes.farmersdelight.cooking(['#forge:raw_beef','carrot','potato'],'farmersdelight:beef_stew',1.0,10*20,BOW)
        event.recipes.create.mixing('farmersdelight:beef_stew',['#forge:raw_beef','carrot','potato',Fluid.of('minecraft:water',250),'bowl']).heated()
        //鸡肉汤
        event.remove({output:"farmersdelight:chicken_soup"})
        event.recipes.farmersdelight.cooking(['#forge:raw_chicken','carrot','#forge:crops/cabbage','#forge:vegetables'],'farmersdelight:chicken_soup',1.0,10*20,BOW)
        event.recipes.create.mixing('farmersdelight:chicken_soup',['#forge:raw_chicken','carrot','#forge:crops/cabbage','#forge:vegetables',Fluid.of('minecraft:water',250),'bowl']).heated()
        //蔬菜汤
        event.remove({output:"farmersdelight:vegetable_soup"})
        event.recipes.farmersdelight.cooking(['carrot','potato','beetroot','#forge:crops/cabbage'],'farmersdelight:vegetable_soup',1.0,10*20,BOW)
        event.recipes.create.mixing('farmersdelight:vegetable_soup',['carrot','potato','beetroot','#forge:crops/cabbage',Fluid.of('minecraft:water',250),'bowl']).heated()
        //鱼肉炖
        event.remove({output:'farmersdelight:fish_stew'})
        event.recipes.farmersdelight.cooking(['#forge:raw_fishes','farmersdelight:tomato_sauce','farmersdelight:onion'],'farmersdelight:fish_stew',1.0,10*20,BOW)
        event.recipes.create.mixing('farmersdelight:fish_stew',['#forge:raw_fishes','farmersdelight:tomato_sauce','farmersdelight:onion',Fluid.of('minecraft:water',250),'bowl']).heated()
        //南瓜汤
        event.remove({output:'farmersdelight:pumpkin_soup'})
        event.recipes.farmersdelight.cooking(['farmersdelight:pumpkin_slice','#forge:crops/cabbage','#forge:raw_pork','#forge:milk'],'farmersdelight:pumpkin_soup',1.0,10*20,BOW)
        event.recipes.create.mixing('farmersdelight:pumpkin_soup',['farmersdelight:pumpkin_slice','#forge:crops/cabbage','#forge:raw_pork','#forge:milk/milk_bottle',Fluid.of('water',250),"bowl"])
        event.recipes.create.mixing('farmersdelight:pumpkin_soup',['farmersdelight:pumpkin_slice','#forge:crops/cabbage','#forge:raw_pork',Fluid.of('milk',250),Fluid.of('water',250),"bowl"]).heated()
        //面条汤
        event.remove({output:'farmersdelight:noodle_soup'})
        event.recipes.farmersdelight.cooking(['farmersdelight:raw_pasta','farmersdelight:fried_egg','dried_kelp','#forge:raw_pork'],'farmersdelight:noodle_soup',1.0,10*20,BOW)
        event.recipes.create.mixing('farmersdelight:noodle_soup',['farmersdelight:raw_pasta','farmersdelight:fried_egg','dried_kelp','#forge:raw_pork',Fluid.of('water',250),"bowl"]).heated()
        //烘焙鳕鱼炖
        event.remove({output:'farmersdelight:baked_cod_stew'})
        event.recipes.farmersdelight.cooking(['#forge:raw_fishes/cod','potato','#forge:eggs','farmersdelight:tomato'],'farmersdelight:baked_cod_stew',1,10*20,BOW)
        event.recipes.create.mixing('farmersdelight:baked_cod_stew',['#forge:raw_fishes/cod','potato','#forge:eggs','tomato',Fluid.of('water',250),"bowl"]).heated()
})